// <auto-generated />
using ConsoleApp1.Intro;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20180118201059_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp1.Intro.Anchor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Anchors");
                });

            modelBuilder.Entity("ConsoleApp1.Intro.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<int?>("NodeId");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Nodes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Node");
                });

            modelBuilder.Entity("ConsoleApp1.Intro.RootNode", b =>
                {
                    b.HasBaseType("ConsoleApp1.Intro.Node");

                    b.Property<int?>("RootId");

                    b.HasIndex("RootId");

                    b.ToTable("RootNode");

                    b.HasDiscriminator().HasValue("RootNode");
                });

            modelBuilder.Entity("ConsoleApp1.Intro.Node", b =>
                {
                    b.HasOne("ConsoleApp1.Intro.Node")
                        .WithMany("Children")
                        .HasForeignKey("NodeId");
                });

            modelBuilder.Entity("ConsoleApp1.Intro.RootNode", b =>
                {
                    b.HasOne("ConsoleApp1.Intro.Anchor", "Root")
                        .WithMany("Properties")
                        .HasForeignKey("RootId");
                });
#pragma warning restore 612, 618
        }
    }
}
